name: trendify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^4.0.3
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.14.2
  lottie: ^2.3.2
  dotlottie_loader: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/languages/
    - assets/motions/

